ype: website  

website:
  title: "Group 11: Trends in Data Science & Business Analytics" 
  navbar:
    left:"
    left:
      - text: "Home"
        href: index.qmd 
      - text: "General Analysis"
        href: data_analysis.qmd
        
format:
  html:
    theme: cosmo 
    theme: cosmo  
    css: styles.css  

execute:
  echo: true
  eval: true
  code-fold: true
