project:
  type: website  

website:
  title: "My Quarto Website"  
  navbar:
    left:  
      - text: "Home"
        href: index.qmd 
      - text: "General Analysis"
        href: data_analysis.qmd
      - text: "References"
        href: references.bib

execute:
  echo: true
  eval: true
  code-fold: true
