project:
  type: website

website:
  title: "Business_Analytics_Trends"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: data_analysis.ipynb
        text: "Data Analysis"
      - href: about.qmd
        text: "About"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

