project:
  type: website  

website:
  title: "Group 11: Trends in Data Science & Business Analytics" 
  navbar:
    left:
      - text: "Home"
        href: index.qmd 
      - text: "Data Analysis"
        href: data_analysis.qmd
  repo-url: "https://github.com/pranjul11garg/ad688-employability-sp25A1-group11"

format:
  html:
    theme: default 
    css: styles.css 
    embed-resources: true

bibliography: references.bib
csl: "./csl/econometrica.csl"

execute:
  echo: true
  eval: true
  code-fold: true
