project:
  type: website  

website:
  title: "Group 11: Trends in Data Science & Business Analytics"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "Data Cleaning"
        href: data_cleaning.ipynb
      - text: "Exploratory Data Analysis"
        href: eda.ipynb
      - href: ml_analysis.ipynb
        text: "ML Methods"
      - href: nlp_methods.ipynb
        text: "NLP Methods"

  repo-url: "https://github.com/pranjul11garg/ad688-employability-sp25A1-group11"

format:
  html:
    theme: default 
    css: styles.css 
    embed-resources: true
    toc: true

bibliography: references.bib
csl: csl/econometrica.csl

execute:
  echo: true
  eval: true
  code-fold: true
