project:
  type: website
  render:
    - index.qmd
    - data_cleaning.qmd
    - eda.ipynb
    - skill_gap_analysis.ipynb
    - rm_model.ipynb
    - analytics_model.qmd
    

website:
  title: "Group 11: Trends in Data Science & Business Analytics"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "Data Cleaning & Exploration"
        menu:
          - text: "Data Cleaning"
            href: data_cleaning.qmd
          - text: "Exploratory Data Analysis"
            href: eda.ipynb
          - text:  "Skill Gap Analysis"
            href: skill_gap_analysis.ipynb
      - text: "ML Methods"
        menu:
          - text: "Supervise Machine Learning"
            href: rm_model.ipynb
          - text: "Unsupervised Machine Learning"
            href: analytic_model.qmd

  repo-url: "https://github.com/pranjul11garg/ad688-employability-sp25A1-group11"

format:
  html:
    theme: cosmo  # Changed to cosmo for a polished look
    css: styles.css
    embed-resources: true
    toc: true
  ipynb: default  # Added to support .ipynb output

bibliography: references.bib
csl: csl/econometrica.csl

execute:
  working-directory: project
  echo: true
  eval: true
  code-fold: true
