project:
  type: website

  # ← now under project
  resources:
    - data/**

  # ← also under project
  render:
    - index.qmd
    - skill_gap.qmd
    - rm_model.ipynb
    - analytics_model.qmd
    - eda_d.qmd

website:
  title: "Trends in Data Science & Business Analytics"
  # … rest of your site config …

format:
  html:
    embed-resources: true
# … etc …
