project:
  type: website  

website:
  title: "Group 11: Trends in Data Science & Business Analytics"  
  navbar:
    left:
      - text: "General Analysis"
        href: data_analysis.qmd
      - text: "References"
        href: references.bib

format:
  html:
    theme: cosmo  
    css: styles.css  

execute:
  echo: true
  eval: true
  code-fold: true
