project:
  type: website  

website:
  sidebar:
    style: "docked"  
    search: true 

      - text: "Home"
        href: index.qmd 
      - href: data_analysis.qmd
        text: "General Analysis"
      - href: career_plan.qmd
        text: "Career Plan"
      - href: references.bib
        text: "References"

execute:
  echo: true
  eval: true
  code-fold: true
