project:
  type: website  

website:
  sidebar:
    style: docked  # No need for quotes around "docked"
    search: true
    contents:  # Added "contents" to define the list properly
      - text: "Home"
        href: index.qmd 
      - text: "General Analysis"
        href: data_cleaning.qmd
      - text: "Career Plan"
        href: career_plan.qmd
      - text: "References"
        href: references.bib

execute:
  echo: true
  eval: true
  code-fold: true
