project:
  type: website
  resources:
  - data/eda_data.csv
  - data/lightcast_job_postings.csv
  render:
    - index.qmd
    - skill_gap.ipynb
    - rm_model.ipynb
    - analytics_model.ipynb

website:
  title: "Trends in Data Science & Business Analytics"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "Data Cleaning & Exploration"
        menu:
          - text: "Skill Gap Analysis"
            href: skill_gap.ipynb
      - text: "Machine Learning Methods"
        menu:
          - text: "Supervise Machine Learning"
            href: rm_model.ipynb
          - text: "Unsupervised Machine Learning"
            href: analytics_model.ipynb

  repo-url: "https://github.com/pranjul11garg/ad688-employability-sp25A1-group11"

format:
  html:
    theme: cosmo  
    css: styles.css
    embed-resources: true
    theme-variables:
      container-max-width: "90rem"   # wider content area
      font-size-base:      "1.15rem" # bump up base font size

  ipynb: default


bibliography: references.bib
csl: csl/econometrica.csl

execute:
  working-directory: project
  echo: true
  eval: true
  code-fold: true



