project:
  type: website   # Ensure it says "website"  
website:
  sidebar:
    style: "docked"  # Sidebar is always visible
    search: true  # Enables search functionality
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Research"
        href: research_introduction.qmd
        contents:
          - research_introduction.qmd
          - trends.qmd
          - literature_review.qmd
      - section: "Data Analysis"
        contents:
          - data_analysis.qmd
          - trends_insights.qmd
      - section: "Career Strategy"
        href: career_plan.qmd
        contents:
          - career_plan.qmd
          - job_market.qmd
      - href: references.qmd
        text: "References"
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true  # Enable right-side Table of Contents for individual pages
bibliography: references.bib
csl: csl/econometrica.csl