project:
  type: website

website:
  title: "Business Analytics Trends"
  navbar:
    right:
      - href: index.qmd
        text: "Home"
      - href: research_introduction.qmd
        text: "Research"
      - href: data_analysis.qmd
        text: "Data Analysis"
      - href: career_plan.qmd
        text: "Career Strategy"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
bibliography: references.bib
csl: csl/econometrica.csl