project:
  type: website
  output-dir: _site
  resources:
    - figures/
  render:
    - index.qmd
    - skill_gap.qmd
    - rm_model.qmd
    - analytics_model.qmd
    - eda_d.qmd
    - data_cleaning.qmd
    - "!finald.qmd"
    - "!dataset_load.ipynb"

website:
  search: false
  title: "Trends in Data Science & Business Analytics"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "Data Cleaning & Exploration"
        menu:
          - text: "Data Cleaning"
            href: data_cleaning.qmd
          - text: "Exploratory Data Analysis"
            href: eda_d.qmd
          - text: "Skill Gap Analysis"
            href: skill_gap.qmd
      - text: "Machine Learning Methods"
        menu:
          - text: "Supervised Machine Learning"
            href: rm_model.qmd
          - text: "Unsupervised Machine Learning"
            href: analytics_model.qmd
  repo-url: "https://github.com/pranjul11garg/ad688-employability-sp25A1-group11"

format:
  html:
    page-layout: full
    theme: cosmo
    css: styles.css
    embed-resources: true
    toc: true
    include-in-header:
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap" rel="stylesheet">       

execute:
  working-directory: project
  echo: true
  eval: true
  code-fold: true
